version: '3.5'
services:
  nginx:
    container_name: api-nginx
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: api-php
    build:
      context: ./nginx
      dockerfile: ./Dockerfile-fpm
    volumes:
      - ./:/var/www/html
